version: '2.1'


services:
  agent-alpine:
    restart: 'no'
    image: puppet/puppet-agent-alpine
    hostname: ${HOSTNAME:-alpine}.localdomain
    volumes:
      - ${BASE_DIR}/agents/${HOSTNAME-alpine}/etc/puppetlabs:/etc/puppetlabs

  agent-ubuntu:
    restart: 'no'
    image: puppet/puppet-agent-ubuntu
    hostname: ${HOSTNAME:-ubuntu}.localdomain
    volumes:
      - ${BASE_DIR}/agents/${HOSTNAME:-ubuntu}/etc/puppetlabs:/etc/puppetlabs

  agent-centos:
    restart: 'no'
    image: puppet/puppet-agent-centos
    hostname: ${HOSTNAME:-centos}.localdomain
    command: pupppet agent -t ${DEBUG}
    volumes:
      - ${BASE_DIR}/agents/${HOSTNAME:-centos}/etc/puppetlabs:/etc/puppetlabs

  agent-debian:
    restart: 'no'
    image: puppet/puppet-agent-debian
    hostname: ${HOSTNAME:-debian}.localdomain
    volumes:
      - ${BASE_DIR}/agents/${HOSTNAME:-debian}/etc/puppetlabs:/etc/puppetlabs
