version: '2.1'


services:
  agent-alpine:
    restart: 'no'
    image: puppet/puppet-agent-alpine
    entrypoint:
      - /bin/sleep
      - '2147483647'
    hostname: ${HOSTNAME:-alpine}.localdomain
    volumes:
      - ${BASE_DIR}/agents/${HOSTNAME:-alpine}/etc/puppetlabs:/etc/puppetlabs

  agent-ubuntu:
    restart: 'no'
    image: puppet/puppet-agent-ubuntu
    entrypoint:
      - /bin/sleep
      - '2147483647'
    hostname: ${HOSTNAME:-ubuntu}.localdomain
    volumes:
      - ${BASE_DIR}/agents/${HOSTNAME:-ubuntu}/etc/puppetlabs:/etc/puppetlabs

  agent-centos:
    restart: 'no'
    image: puppet/puppet-agent-centos
    hostname: ${HOSTNAME:-centos}.localdomain
    entrypoint:
      - /bin/sleep
      - '2147483647'
    volumes:
      - ${BASE_DIR}/agents/${HOSTNAME:-centos}/etc/puppetlabs:/etc/puppetlabs

  agent-debian:
    restart: 'no'
    image: puppet/puppet-agent-debian
    hostname: ${HOSTNAME:-debian}.localdomain
    entrypoint:
      - /bin/sleep
      - '2147483647'
    volumes:
      - ${BASE_DIR}/agents/${HOSTNAME:-debian}/etc/puppetlabs:/etc/puppetlabs
