version: '2.1'


services:
  agent-alpine:
    restart: 'no'
    image: puppet/puppet-agent-alpine
    entrypoint:
      - /usr/bin/puppet
      - agent
      - '--no-daemonize'
      - '-v'
      - '--summarize'

  agent-ubuntu:
    restart: 'no'
    image: ubuntu-devel
    entrypoint:
      - /opt/puppetlabs/puppet/bin/puppet
      - agent
      - '--no-daemonize'
      - '-v'
      - '--summarize'

  agent-centos:
    restart: 'no'
    image: puppet/puppet-agent-centos
    entrypoint:
      - /opt/puppetlabs/puppet/bin/puppet
      - agent
      - '--no-daemonize'
      - '-v'
      - '--summarize'

  agent-debian:
    restart: 'no'
    image: puppet/puppet-agent-debian
    entrypoint:
      - /opt/puppetlabs/puppet/bin/puppet
      - agent
      - '--no-daemonize'
      - '-v'
      - '--summarize'
