version: '2'

services:
  puppet:
    restart: always
    hostname: puppet
    image: puppet/puppetserver:2.4.0
    ports:
      - 8140
    volumes:
      - /srv/docker/plabs/code:/etc/puppetlabs/code/
      - /srv/docker/plabs/puppet/ssl:/etc/puppetlabs/puppet/ssl/
    #  - /srv/docker/plabs/puppet/serverdata:/opt/puppetlabs/server/data/puppetserver/
    # In some cases unqualified hostnames can have the .local suffix
    # added, I've seen this under Docker of Mac Beta for instance.
    # Due to needing to access PuppetDB on same hostame as signed in the
    # certificate you may need to uncommant the following lines
    environment:
      - PUPPETDB_SERVER_URLS=https://puppetdb:8081
    #links:
    #  - puppetdb:puppet.localdomain

  puppetdbpostgres:
    restart: always
    container_name: postgres
    image: puppet/puppetdb-postgres
    environment:
      - POSTGRES_PASSWORD=puppetdb
      - POSTGRES_USER=puppetdb
    expose:
      - 5432
    volumes:
      - /srv/docker/plabs/puppetdb-postgres/data:/var/lib/postgresql/data/

  puppetdb:
    restart: always
    hostname: puppetdb
    image: puppetdb
    ports:
      - 8080:8080
      - 8081:8081
    volumes:
      - /srv/docker/plabs/puppetdb/ssl:/etc/puppetlabs/puppet/ssl/
    depends_on:
      - puppet

  puppetboard:
    restart: always
    image: puppetboard
    ports:
      - 80:80
    environment:
      - PUPPETDB_HOST=puppetdb
      - PUPPETDB_PORT=8080
      - PUPPETDB_SSL_VERIFY=False
      - ENABLE_CATALOG=True
    depends_on:
      - puppetdb

  agent-alpine:
    restart: never
    image: puppet/puppet-agent-alpine
    hostname: alpine.localdomain
    volumes:
      - /srv/docker/plabs/agents/alpine/etc/puppetlabs:/etc/puppetlabs

  agent-ubuntu:
    restart: never
    image: puppet/puppet-agent-ubuntu
    hostname: ubuntu.localdomain
    volumes:
      - /srv/docker/plabs/agents/ubuntu/etc/puppetlabs:/etc/puppetlabs

  agent-centos:
    restart: never
    image: puppet/puppet-agent-centos
    hostname: centos.localdomain
    volumes:
      - /srv/docker/plabs/agents/centos/etc/puppetlabs:/etc/puppetlabs

  agent-debian:
    restart: never
    image: puppet/puppet-agent-debian
    hostname: debian.localdomain
    volumes:
      - /srv/docker/plabs/agents/debian/etc/puppetlabs:/etc/puppetlabs

  puppetexplorer:
    restart: always
    image: puppet/puppetexplorer
    ports:
      - 8000:80
    read_only: true
