version: '2.1'

services:
  puppet:
    restart: always
    hostname: puppet
    image: ${PUPPET_SERVER_IMAGE}${PUPPET_SERVER_VERSION}
    ports:
      - 8140
    volumes:
      - ${CODE_DIR}:/etc/puppetlabs/code/
      - ${BASE_DIR}/puppet/ssl:/etc/puppetlabs/puppet/ssl/
    #  - ${BASE_DIR}/puppet/serverdata:/opt/puppetlabs/server/data/puppetserver/
    # In some cases unqualified hostnames can have the .local suffix
    # added, I've seen this under Docker of Mac Beta for instance.
    # Due to needing to access PuppetDB on same hostame as signed in the
    # certificate you may need to uncommant the following lines
    environment:
      - PUPPETDB_SERVER_URLS=https://puppetdb:8081
    #links:
    #  - puppetdb:puppet.localdomain

  puppetdbpostgres:
    restart: always
    container_name: postgres
    image: ${POSTGRES_IMAGE}${POSTGRES_VERSION}
    environment:
      - POSTGRES_PASSWORD=puppetdb
      - POSTGRES_USER=puppetdb
    expose:
      - 5432
    volumes:
      - ${BASE_DIR}/puppetdb-postgres/data:/var/lib/postgresql/data/

  puppetdb:
    restart: always
    hostname: puppetdb
    image: ${PUPPETDB_IMAGE}${PUPPETDB_VERSION}
    ports:
      - 8080:8080
      - 8081:8081
    volumes:
      - ${BASE_DIR}/puppetdb/ssl:/etc/puppetlabs/puppet/ssl/
    depends_on:
      - puppet

  puppetboard:
    restart: always
    image: ${PUPPETBOARD_IMAGE}${PUPPETBOARD_VERSION}
    ports:
      - ${PUPPETBOARD_PORT}:80
    environment:
      - PUPPETDB_HOST=puppetdb
      - PUPPETDB_PORT=8080
      - PUPPETDB_SSL_VERIFY=False
      - ENABLE_CATALOG=True
    depends_on:
      - puppetdb
